### ISSUE TITLE
do u know where is the blabla messages text data file?

### ISSUE THREAD

**Issue by tttleon** [Nikke-db/Nikke-db.github.io#10]
i want to make a blabla messages simulator,but i can not find the text file location.
i decrypted the assets with the [svatyvabin/NikkeTools](https://github.com/svatyvabin/NikkeTools) and load file with the [Perfare/AssetStudio](https://github.com/Perfare/AssetStudio).but all i can find is the spine2d type file。i even did not find the main story text file.
![QQ截图20230803172428](https://github.com/Nikke-db/Nikke-db.github.io/assets/66937093/907a51a9-af61-45b4-9b5c-475a1d138df3)

**Comment by Nikke-db** [comment]
Hi, I am unsure of the exact file names, but to begin with I'll tell you good luck on your features !  

You seem to be extracting from a mobile device or android emulator, I'd advise you to check out the Unity or UnityCache folder ( I forgot which one is the important folder ) 
One of them have about 3gb of unity data that can directly be loaded into assetstudio without the need of nikketools.

Once loaded, a quick search of "locale_" will give you lots of json corresponding to lots of texts, including story, blabla, subquests, advises and more in your locale language ( if you are en it will be english files, if you want japanese you need to switch the language in game then reload the folder ) 

The files by themselves aren't that easy to use, you need to link one file to another throught object m_id to find back who's talking or who is it about, there's usually a "shared data" file corresponding for each "locale_xxx" file.

It is a huge hassle to link the files from one to another, and you'll most likely need to find files I don't know to track back m_id to character names. 

I hope you will manage to find the files and motivation to bring the project to it's end ( I kind of did not which is why my story page is pretty much dead and will never be finished )

**Comment by Nikke-db** [comment]
closed due to inactivity

**Comment by Rhystic1** [comment]
@Nikke-db I believe the Locale files are now different. They appear as ".lsc" files (with accompanying, much smaller ".nds" files) and their header is "NKDB". These files cannot be decrypted with NKDB-Tools. Do you know how they can be opened/decrypted? Thank you very much!

**Comment by Koshirei** [comment]
the nkdb decryptor is private. I know how to translate them into a sqlite database but I won't share it. for one because the software is private and two because there's a big message saying I won't help people datamining
