### ISSUE TITLE
Modernia Second Second Affection missing action animation

### ISSUE THREAD

**Issue by Darthassine** [Nikke-db/Nikke-db.github.io#14]
After the latest update Modernia Second Affection have still no action (touch) animation

**Comment by Koshirei** [comment]
the update will be live in a minute or two, you might need to do a cache refresh if it doesn't appear.
sadly this is one of the animations that reduces the size of the character to be shown fully, so making a zoom will blur modernia if you want to see it "fullscreen". 
if you need a single frame I suggest the screenshot feature, otherwise it might be time for me to look into a better zooming system.

**Comment by Darthassine** [comment]
Thank you ^^, well i have Spine Pro ^^
