### ISSUE TITLE
Any way to download the Visualizer animations not as .webm while keeping transparency? (For video editing)

### ISSUE THREAD

**Issue by Meladoom** [Nikke-db/Nikke-db.github.io#16]
webm is really cool and is the future, but as of now it's not supported by anything I tried
premiere pro 2024, kdenlive, davinci resolve.
I managed to import webms to my video editors' project files after some tweaks, but the transparency doesn't seem to work
ffmpeg and imagemagick also didn't help

The worst way to do this would be to just generate a downloadable archive with all 60fps .png screenshots of your selected character (transparency works perfectly on them), that you can convert to anything through Blender's image sequence yourself

**Comment by Koshirei** [comment]
sounds unreasonable, especially when webm is the only video format that accepts transparent pixels.

The only other THEORICAL format that could handle transprent pixels would be webp and gif but afaik neither handles pixels with alpha < 255 ( similar to webm anyway ).

Why would you need these in a different format ?

Couldn't you use a recording software such as OBS with a green background color, and in an editing software you do chroma key removal ?

**Comment by Meladoom** [comment]
> Couldn't you use a recording software such as OBS with a green background color, and in an editing software you do chroma key removal ?

Never thought that I'll have to make a CAM-Rip xd
Tried to remove the greenscreen in Premiere, kinda works! But not perfectly. Finding the perfect value for every setting to achieve the the .png quality that you can already download from the website would take insane amount time, at least for someone who never used it. Also it might be limited to the user's monitor resolution. Let alone that HQ sprites preview are pretty laggy on old hardware. (which is weird, because the game itself works flawlessly on the same hardware. max settings obv)

Would be nice to have hotkeys, such as "stop loop" and "play" when the UI is hidden. (tried to use uBlock Origin's element picker to remove the top part. also changed the scale to 50%. worked nice, but the timeline gets bugged a little)
Ones mentioned here do not seem to work http://esotericsoftware.com/spine-cheat-sheet

My goal is to get 2 animations from start to finish with frame-perfect length on Rosanna: Chic Ocean. To combine them into a smooth transition (first-second-first animation)
As I noticed, bg_idle completely freezes her.

> webm is the only video format that accepts transparent pixels

Tried to export the OBS recording with greenscreen removed as .mov, transparency works in every video editor, but once again - removed greenscreen is far from perfect. Also insane filesize (x1000).

**.apng might work**

**Comment by Koshirei** [comment]
> Let alone that HQ sprites preview are pretty laggy on old hardware. (which is weird, because the game itself works flawlessly on the same hardware. max settings obv)

You are comparing Unity, which was made to render heavy assets, to a webpage that bruteforces the display.
Web browser have a lot more restrictions for cpu & ram usage and are not made at all to render such things at that high quality.

> Ones mentioned here do not seem to work http://esotericsoftware.com/spine-cheat-sheet

This is a cheat sheet for the spine software, I am not using the spine software, I am using spine web player.
Spine web player have zero default shortcuts because it'd impact the UX of the app (imagine writing a sentence in a page that have a spine asset running, every time you'd press space it'd stop and resume the animation ... )
Every action and hotkeys have been hardcoded by myself, spine player do not offer drag & scroll asset movement, neither zoom, or dynamic background coloring.
Adding hotkeys for stop loop and play could be interesting but honestly I won't waste my time on it as I don't see a single reason for it? or you could make some tampermonkey scripts that'd do this, should be quick enough with basic JS knowledge. Cropping a video to the wished frame should also be trivial in an editing software.


Either way, I still don't see why a screen record wouldn't work. In which universe would you need animations that are bigger than a 1920x1080p resolution? considering that'd be your file resolution in a 1080p monitor full screen.

If you have a project in which you really want to insert nikke animation, check out if a spine runtime exists for your software , pull my repository and do it the correct way through spine itself
